code-generator:
  author: 赌狗
  output-dir: ./src/main/java
  parent-package: com.dragon.pay
  module-name: merchant
  base-package: com.dragon.pay.merchant
  db:
    url: jdbc:mysql://localhost:3306/dragon-pay?serverTimezone=Asia/Shanghai
    username: root
    password: root
  include-tables:
    - merchant_account
#    - user
  table-prefix: sys_
